- name: Install Java
  yum:
    name: java-11-amazon-corretto-devel
    state: present

- name: Download Tomcat
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.53/bin/apache-tomcat-9.0.53.tar.gz"
    dest: "/tmp/tomcat.tar.gz"
    
- name: Extract Tomcat
  unarchive:
    src: /tmp/tomcat.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create symlink
  file:
    src: /opt/apache-tomcat-9.0.53
    dest: /opt/tomcat
    state: link

- name: Start Tomcat
  command: /opt/tomcat/bin/startup.sh